#+STARTUP: beamer
#+TITLE: El triunfo del Yo pleno
#+AUTHOR: Hans Sigrist
#+EMAIL: hans.sigrist@uac.cl
#+OPTIONS: H:3 toc:nil  num:t tags:nil
#+LATEX_CLASS: hytalk
#+BEAMER_THEME: Hytex
#+BEAMER_HEADER: \date{}
#+BEAMER_HEADER: \institute[UAC]{UAC}
#+DESCRIPTION: La transformación como acto de vida
#+KEYWORDS: comunicación efectiva
#+SUBTITLE: Estrategias para promover una transfromación personal
#+LANGUAGE: es
#+OPTIONS: reveal_center:t reveal_progress:t reveal_history:t reveal_control:t
#+OPTIONS: reveal_mathjax:t reveal_rolling_links:t reveal_keyboard:t reveal_overview:t num:nil
#+OPTIONS: reveal_width:1200 reveal_height:800
#+REVEAL_MARGIN: 0.2
#+REVEAL_MIN_SCALE: 0.5
#+REVEAL_MAX_SCALE: 2.5
#+REVEAL_TRANS: none
#+REVEAL_THEME: simple
#+REVEAL_HLEVEL: 999
#+REVEAL_ROOT: http://cdn.jsdelivr.net/reveal.js/3.0.0/
#+REVEAL_EXTRA_CSS: simple.css

* El triunfo del Yo pleno

* En su libro "Triunfo. Una guía para alcanzar la plenitud", Robin Sharma, uno de los mayores gurúes mundiales en liderazgo, plantea la necesidad de no ir por la vida, sin experimentar una transformación. Para ello propone algunas estrategias, entre las que destacan:

* Sé tan bueno que nadie pueda ignorarte. La persona entregada, increíblemente buena en lo que hace, no puede pasar inadvertida.

* Piensa en grande. Si piensas en grande tu comportamiento se elevará; si piensas con mediocridad, tus actos serán mediocres.

* Nunca dejes para mañana lo que se puede hacer hoy. Si lo haces, sólo te estarás limitando.

* Hazte preguntas clave (¿Por qué prorrogo?, ¿me preocupan las opiniones de los demás?, ¿agrego o resto valor a mi equipo?, etc.).

* Exígete a ti mismo. Si lo haces, subirás al siguiente nivel y los demás no podrían hacer algo distinto (modelaje).

* Utiliza el nombre de pila de la persona. Esto es muy importante, pues indica que esa persona te importa y de paso, le estás diciendo "llámame por mi nombre".

* Potencia tu marca personal. Trabaja una marca que sea rompedora, que te muestre original, de tal manera que tu nombre quede resonando en los demás.

* Desea crecer. El crecimiento es la única prueba de que existimos. No te limites a vivir la vida; dirígela.

* Sé sorprendentemente diferente. Sé creativo; sé consciente de qué te hace diferente de los demás.

* Ayuda a otros a alcanzar su excelencia. Para crecer hay que dar. Así, recibirás (principio de reciprocidad).

* Deja tu impronta. Cuando las cosas se hacen con pasión, el proceso se disfruta con intensidad y no habrá nada que hayas tocado que no huela a ti. Pero, dejar nuestra huella, toma su tiempo (autodisciplina).
