#+STARTUP: beamer
#+TITLE: Episodios académicos que relevan procesos comunicativos
#+AUTHOR: Hans Sigrist
#+EMAIL: hans.sigrist@uac.cl
#+OPTIONS: H:1 toc:nil num:nil tags:nil
#+LATEX_CLASS: hytalk
#+BEAMER_THEME: Hytex
#+BEAMER_HEADER: \date{}
#+BEAMER_HEADER: \institute[UAC]{UAC}
#+DESCRIPTION: Episodios que requieren procesos comunicativos
#+KEYWORDS: ejercicio practico
#+OPTIONS: reveal_center:t reveal_progress:t reveal_history:t reveal_control:t
#+OPTIONS: reveal_mathjax:t reveal_rolling_links:t reveal_keyboard:t reveal_overview:t num:nil
#+OPTIONS: reveal_width:1200 reveal_height:800
#+REVEAL_MARGIN: 0.2
#+REVEAL_MIN_SCALE: 0.5
#+REVEAL_MAX_SCALE: 2.5
#+REVEAL_TRANS: none
#+REVEAL_THEME: simple
#+REVEAL_HLEVEL: 999
#+REVEAL_ROOT: http://cdn.jsdelivr.net/reveal.js/3.0.0/
#+REVEAL_EXTRA_CSS: simple.css

* Episodios académicos que relevan procesos comunicativos
No todo es negativo, existen muy buenos diálogos comunicativos y/o asertivos, además de situaciones en la que se evidencia la *escucha activa*. Lo que he tenido oportunidad de observar.

* Consigna

Identifique en estas oraciones/situaciones los actores en el mensaje, señalando quiénes manifiestan escucha activa, lenguaje culto-formal, quiénes retroalimentan, quiénes son asertivos, etc. Junto con ello, evalúe si Usted utiliza estos elementos comunicativos en situaciones comunicativas cotidianas. 

* 
Profesor, buenos días. Le pido excuse mi ausencia a la clase hoy en la noche, debido a una situación laboral ya agendada.
* 
Hablemos de a uno por favor compañeros, sino nadie entenderá en qué vamos a quedar.
* 
Veo que todos trajeron su computador; obvio profesor, Usted lo solicitó así la semana pasada y nosotros se lo trasmitimos a los compañeros ausentes.
* 
Hola amiga!! gracias por avisar que había que traer calculadora científica, porque me la consigo con mi papá.
* 
Ay amiga!! gracias por avisar que el profe no va hoy, estaba a punto de tomar el bus a la U.
* 
Profesor, buenos días. Disculpe la interrupción, pero queríamos saber si Usted nos autoriza a mechonear a sus alumnos.
