#+STARTUP: beamer
#+TITLE: Episodios académicos que requieren procesos comunicativos
#+AUTHOR: Hans Sigrist
#+EMAIL: hans.sigrist@uac.cl
#+OPTIONS: H:1 toc:nil num:nil tags:nil
#+LATEX_CLASS: hytalk
#+BEAMER_THEME: Hytex
#+BEAMER_HEADER: \date{}
#+BEAMER_HEADER: \institute[UAC]{UAC}
#+DESCRIPTION: Episodios que requieren procesos comunicativos
#+KEYWORDS: ejercicio practico
#+OPTIONS: reveal_center:t reveal_progress:t reveal_history:t reveal_control:t
#+OPTIONS: reveal_mathjax:t reveal_rolling_links:t reveal_keyboard:t reveal_overview:t num:nil
#+OPTIONS: reveal_width:1200 reveal_height:800
#+REVEAL_MARGIN: 0.2
#+REVEAL_MIN_SCALE: 0.5
#+REVEAL_MAX_SCALE: 2.5
#+REVEAL_TRANS: none
#+REVEAL_THEME: simple
#+REVEAL_HLEVEL: 999
#+REVEAL_ROOT: http://cdn.jsdelivr.net/reveal.js/3.0.0/
#+REVEAL_EXTRA_CSS: simple.css


* Episodios académicos que requieren de procesos comunicativos

Durante el primer semestre recién pasado, tuve oportunidad de observar diversos procesos que requieren de nuestra atención. Todos somos actores de estos procesos, tanto Ustedes, como yo, como otros/as. Nadie es ajeno a la comunicación, sin embargo, no todos utilizan procesos comunicativos en el contexto académico de una forma crítica y/o reflexiva. No olvide la máxima de Comunicación Efectiva: nunca utilizamos juicios valóricos, además dejamos las emociones de lado: éstos dos aspectos no son constitutivos de objetividad y solo aportan sesgo. Lo que he tenido oportunidad de observar, me han relatado o le han ocurrido a otros estudiantes.

* Consigna

Identifique en estas oraciones/situaciones los actores en el mensaje, señalando quiénes manifiestan enfado, juicios valóricos, quiénes ejercen poder, quiénes son una amenaza, etc. Junto con ello, proponga una solución a estos actos comunicativos que se acerque a lo que hemos entendido por comunicación efectiva.
* 
El estudiante no podrá venir a clases nunca los días sábado y lo comunica con un recado para el profesor.
* 
El profesor faltó a clases, no lo comunicó con anticipación, lo esperamos todos y nos fuimos enojados, porque el profesor es irresponsable y mala gente.
* 
El profesor tomó una prueba, sólo para perjudicarnos.
* 
En esta Universidad son todos chantas. Sólo para cobrar tienen tiempo.
* 
Nadie avisó que había clases en esta otra sala. No sé para qué publican horarios si los cambian y no los corrigen.
* 
El profe puso en su face, que no va a venir hoy día.
* 
El profe dejó pasar a un colega que sólo generó confusión en la sala y además se burló de nosotros.
* 
Como yo soy adulto y profesional trato de una manera simétrica al profe, total tengo su misma edad, lo tuteo, lo increpo, le hago señalamientos y como no me gustó le dije lo que sentí.
* 
El profe lee, lee y lee las presentaciones Power Point. Como si nosotros no supiéramos leer.
* 
Me leí la materia de la prueba anoche pero no entendí nada. ¿Quién me explica?
